// Code generated by ifacemaker; DO NOT EDIT.

package sns

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/sns"
)

// SNSClient is a wrapper interface for the [github.com/aws/aws-sdk-go-v2/service/sns.Client].
// Client provides the API client to make operations call for Amazon Simple
// Notification Service.
type SNSClient interface {
	// Options returns a copy of the client configuration.
	//
	// Callers SHOULD NOT perform mutations on any inner structures within client
	// config. Config overrides should instead be made on a per-operation basis through
	// functional options.
	Options() sns.Options
	// Adds a statement to a topic's access control policy, granting access for the
	// specified Amazon Web Services accounts to the specified actions.
	//
	// To remove the ability to change topic permissions, you must deny permissions to
	// the AddPermission , RemovePermission , and SetTopicAttributes actions in your
	// IAM policy.
	AddPermission(ctx context.Context, params *sns.AddPermissionInput, optFns ...func(*sns.Options)) (*sns.AddPermissionOutput, error)
	// Accepts a phone number and indicates whether the phone holder has opted out of
	// receiving SMS messages from your Amazon Web Services account. You cannot send
	// SMS messages to a number that is opted out.
	//
	// To resume sending messages, you can opt in the number by using the
	// OptInPhoneNumber action.
	CheckIfPhoneNumberIsOptedOut(ctx context.Context, params *sns.CheckIfPhoneNumberIsOptedOutInput, optFns ...func(*sns.Options)) (*sns.CheckIfPhoneNumberIsOptedOutOutput, error)
	// Verifies an endpoint owner's intent to receive messages by validating the token
	// sent to the endpoint by an earlier Subscribe action. If the token is valid, the
	// action creates a new subscription and returns its Amazon Resource Name (ARN).
	// This call requires an AWS signature only when the AuthenticateOnUnsubscribe
	// flag is set to "true".
	ConfirmSubscription(ctx context.Context, params *sns.ConfirmSubscriptionInput, optFns ...func(*sns.Options)) (*sns.ConfirmSubscriptionOutput, error)
	// Creates a platform application object for one of the supported push
	// notification services, such as APNS and GCM (Firebase Cloud Messaging), to which
	// devices and mobile apps may register. You must specify PlatformPrincipal and
	// PlatformCredential attributes when using the CreatePlatformApplication action.
	//
	// PlatformPrincipal and PlatformCredential are received from the notification
	// service.
	//
	//   - For ADM, PlatformPrincipal is client id and PlatformCredential is client
	//     secret .
	//
	//   - For APNS and APNS_SANDBOX using certificate credentials, PlatformPrincipal
	//     is SSL certificate and PlatformCredential is private key .
	//
	//   - For APNS and APNS_SANDBOX using token credentials, PlatformPrincipal is
	//     signing key ID and PlatformCredential is signing key .
	//
	//   - For Baidu, PlatformPrincipal is API key and PlatformCredential is secret key
	//     .
	//
	//   - For GCM (Firebase Cloud Messaging) using key credentials, there is no
	//     PlatformPrincipal . The PlatformCredential is API key .
	//
	//   - For GCM (Firebase Cloud Messaging) using token credentials, there is no
	//     PlatformPrincipal . The PlatformCredential is a JSON formatted private key
	//     file. When using the Amazon Web Services CLI, the file must be in string format
	//     and special characters must be ignored. To format the file correctly, Amazon SNS
	//     recommends using the following command: SERVICE_JSON=`jq @json <<< cat
	//     service.json` .
	//
	//   - For MPNS, PlatformPrincipal is TLS certificate and PlatformCredential is
	//     private key .
	//
	//   - For WNS, PlatformPrincipal is Package Security Identifier and
	//     PlatformCredential is secret key .
	//
	// You can use the returned PlatformApplicationArn as an attribute for the
	// CreatePlatformEndpoint action.
	CreatePlatformApplication(ctx context.Context, params *sns.CreatePlatformApplicationInput, optFns ...func(*sns.Options)) (*sns.CreatePlatformApplicationOutput, error)
	// Creates an endpoint for a device and mobile app on one of the supported push
	// notification services, such as GCM (Firebase Cloud Messaging) and APNS.
	// CreatePlatformEndpoint requires the PlatformApplicationArn that is returned
	// from CreatePlatformApplication . You can use the returned EndpointArn to send a
	// message to a mobile app or by the Subscribe action for subscription to a topic.
	// The CreatePlatformEndpoint action is idempotent, so if the requester already
	// owns an endpoint with the same device token and attributes, that endpoint's ARN
	// is returned without creating a new endpoint. For more information, see [Using Amazon SNS Mobile Push Notifications].
	//
	// When using CreatePlatformEndpoint with Baidu, two attributes must be provided:
	// ChannelId and UserId. The token field must also contain the ChannelId. For more
	// information, see [Creating an Amazon SNS Endpoint for Baidu].
	//
	// [Creating an Amazon SNS Endpoint for Baidu]: https://docs.aws.amazon.com/sns/latest/dg/SNSMobilePushBaiduEndpoint.html
	// [Using Amazon SNS Mobile Push Notifications]: https://docs.aws.amazon.com/sns/latest/dg/SNSMobilePush.html
	CreatePlatformEndpoint(ctx context.Context, params *sns.CreatePlatformEndpointInput, optFns ...func(*sns.Options)) (*sns.CreatePlatformEndpointOutput, error)
	// Adds a destination phone number to an Amazon Web Services account in the SMS
	// sandbox and sends a one-time password (OTP) to that phone number.
	//
	// When you start using Amazon SNS to send SMS messages, your Amazon Web Services
	// account is in the SMS sandbox. The SMS sandbox provides a safe environment for
	// you to try Amazon SNS features without risking your reputation as an SMS sender.
	// While your Amazon Web Services account is in the SMS sandbox, you can use all of
	// the features of Amazon SNS. However, you can send SMS messages only to verified
	// destination phone numbers. For more information, including how to move out of
	// the sandbox to send messages without restrictions, see [SMS sandbox]in the Amazon SNS
	// Developer Guide.
	//
	// [SMS sandbox]: https://docs.aws.amazon.com/sns/latest/dg/sns-sms-sandbox.html
	CreateSMSSandboxPhoneNumber(ctx context.Context, params *sns.CreateSMSSandboxPhoneNumberInput, optFns ...func(*sns.Options)) (*sns.CreateSMSSandboxPhoneNumberOutput, error)
	// Creates a topic to which notifications can be published. Users can create at
	// most 100,000 standard topics (at most 1,000 FIFO topics). For more information,
	// see [Creating an Amazon SNS topic]in the Amazon SNS Developer Guide. This action is idempotent, so if the
	// requester already owns a topic with the specified name, that topic's ARN is
	// returned without creating a new topic.
	//
	// [Creating an Amazon SNS topic]: https://docs.aws.amazon.com/sns/latest/dg/sns-create-topic.html
	CreateTopic(ctx context.Context, params *sns.CreateTopicInput, optFns ...func(*sns.Options)) (*sns.CreateTopicOutput, error)
	// Deletes the endpoint for a device and mobile app from Amazon SNS. This action
	// is idempotent. For more information, see [Using Amazon SNS Mobile Push Notifications].
	//
	// When you delete an endpoint that is also subscribed to a topic, then you must
	// also unsubscribe the endpoint from the topic.
	//
	// [Using Amazon SNS Mobile Push Notifications]: https://docs.aws.amazon.com/sns/latest/dg/SNSMobilePush.html
	DeleteEndpoint(ctx context.Context, params *sns.DeleteEndpointInput, optFns ...func(*sns.Options)) (*sns.DeleteEndpointOutput, error)
	// Deletes a platform application object for one of the supported push
	// notification services, such as APNS and GCM (Firebase Cloud Messaging). For more
	// information, see [Using Amazon SNS Mobile Push Notifications].
	//
	// [Using Amazon SNS Mobile Push Notifications]: https://docs.aws.amazon.com/sns/latest/dg/SNSMobilePush.html
	DeletePlatformApplication(ctx context.Context, params *sns.DeletePlatformApplicationInput, optFns ...func(*sns.Options)) (*sns.DeletePlatformApplicationOutput, error)
	// Deletes an Amazon Web Services account's verified or pending phone number from
	// the SMS sandbox.
	//
	// When you start using Amazon SNS to send SMS messages, your Amazon Web Services
	// account is in the SMS sandbox. The SMS sandbox provides a safe environment for
	// you to try Amazon SNS features without risking your reputation as an SMS sender.
	// While your Amazon Web Services account is in the SMS sandbox, you can use all of
	// the features of Amazon SNS. However, you can send SMS messages only to verified
	// destination phone numbers. For more information, including how to move out of
	// the sandbox to send messages without restrictions, see [SMS sandbox]in the Amazon SNS
	// Developer Guide.
	//
	// [SMS sandbox]: https://docs.aws.amazon.com/sns/latest/dg/sns-sms-sandbox.html
	DeleteSMSSandboxPhoneNumber(ctx context.Context, params *sns.DeleteSMSSandboxPhoneNumberInput, optFns ...func(*sns.Options)) (*sns.DeleteSMSSandboxPhoneNumberOutput, error)
	// Deletes a topic and all its subscriptions. Deleting a topic might prevent some
	// messages previously sent to the topic from being delivered to subscribers. This
	// action is idempotent, so deleting a topic that does not exist does not result in
	// an error.
	DeleteTopic(ctx context.Context, params *sns.DeleteTopicInput, optFns ...func(*sns.Options)) (*sns.DeleteTopicOutput, error)
	// Retrieves the specified inline DataProtectionPolicy document that is stored in
	// the specified Amazon SNS topic.
	GetDataProtectionPolicy(ctx context.Context, params *sns.GetDataProtectionPolicyInput, optFns ...func(*sns.Options)) (*sns.GetDataProtectionPolicyOutput, error)
	// Retrieves the endpoint attributes for a device on one of the supported push
	// notification services, such as GCM (Firebase Cloud Messaging) and APNS. For more
	// information, see [Using Amazon SNS Mobile Push Notifications].
	//
	// [Using Amazon SNS Mobile Push Notifications]: https://docs.aws.amazon.com/sns/latest/dg/SNSMobilePush.html
	GetEndpointAttributes(ctx context.Context, params *sns.GetEndpointAttributesInput, optFns ...func(*sns.Options)) (*sns.GetEndpointAttributesOutput, error)
	// Retrieves the attributes of the platform application object for the supported
	// push notification services, such as APNS and GCM (Firebase Cloud Messaging). For
	// more information, see [Using Amazon SNS Mobile Push Notifications].
	//
	// [Using Amazon SNS Mobile Push Notifications]: https://docs.aws.amazon.com/sns/latest/dg/SNSMobilePush.html
	GetPlatformApplicationAttributes(ctx context.Context, params *sns.GetPlatformApplicationAttributesInput, optFns ...func(*sns.Options)) (*sns.GetPlatformApplicationAttributesOutput, error)
	// Returns the settings for sending SMS messages from your Amazon Web Services
	// account.
	//
	// These settings are set with the SetSMSAttributes action.
	GetSMSAttributes(ctx context.Context, params *sns.GetSMSAttributesInput, optFns ...func(*sns.Options)) (*sns.GetSMSAttributesOutput, error)
	// Retrieves the SMS sandbox status for the calling Amazon Web Services account in
	// the target Amazon Web Services Region.
	//
	// When you start using Amazon SNS to send SMS messages, your Amazon Web Services
	// account is in the SMS sandbox. The SMS sandbox provides a safe environment for
	// you to try Amazon SNS features without risking your reputation as an SMS sender.
	// While your Amazon Web Services account is in the SMS sandbox, you can use all of
	// the features of Amazon SNS. However, you can send SMS messages only to verified
	// destination phone numbers. For more information, including how to move out of
	// the sandbox to send messages without restrictions, see [SMS sandbox]in the Amazon SNS
	// Developer Guide.
	//
	// [SMS sandbox]: https://docs.aws.amazon.com/sns/latest/dg/sns-sms-sandbox.html
	GetSMSSandboxAccountStatus(ctx context.Context, params *sns.GetSMSSandboxAccountStatusInput, optFns ...func(*sns.Options)) (*sns.GetSMSSandboxAccountStatusOutput, error)
	// Returns all of the properties of a subscription.
	GetSubscriptionAttributes(ctx context.Context, params *sns.GetSubscriptionAttributesInput, optFns ...func(*sns.Options)) (*sns.GetSubscriptionAttributesOutput, error)
	// Returns all of the properties of a topic. Topic properties returned might
	// differ based on the authorization of the user.
	GetTopicAttributes(ctx context.Context, params *sns.GetTopicAttributesInput, optFns ...func(*sns.Options)) (*sns.GetTopicAttributesOutput, error)
	// Lists the endpoints and endpoint attributes for devices in a supported push
	// notification service, such as GCM (Firebase Cloud Messaging) and APNS. The
	// results for ListEndpointsByPlatformApplication are paginated and return a
	// limited list of endpoints, up to 100. If additional records are available after
	// the first page results, then a NextToken string will be returned. To receive the
	// next page, you call ListEndpointsByPlatformApplication again using the
	// NextToken string received from the previous call. When there are no more records
	// to return, NextToken will be null. For more information, see [Using Amazon SNS Mobile Push Notifications].
	//
	// This action is throttled at 30 transactions per second (TPS).
	//
	// [Using Amazon SNS Mobile Push Notifications]: https://docs.aws.amazon.com/sns/latest/dg/SNSMobilePush.html
	ListEndpointsByPlatformApplication(ctx context.Context, params *sns.ListEndpointsByPlatformApplicationInput, optFns ...func(*sns.Options)) (*sns.ListEndpointsByPlatformApplicationOutput, error)
	// Lists the calling Amazon Web Services account's dedicated origination numbers
	// and their metadata. For more information about origination numbers, see [Origination numbers]in the
	// Amazon SNS Developer Guide.
	//
	// [Origination numbers]: https://docs.aws.amazon.com/sns/latest/dg/channels-sms-originating-identities-origination-numbers.html
	ListOriginationNumbers(ctx context.Context, params *sns.ListOriginationNumbersInput, optFns ...func(*sns.Options)) (*sns.ListOriginationNumbersOutput, error)
	// Returns a list of phone numbers that are opted out, meaning you cannot send SMS
	// messages to them.
	//
	// The results for ListPhoneNumbersOptedOut are paginated, and each page returns
	// up to 100 phone numbers. If additional phone numbers are available after the
	// first page of results, then a NextToken string will be returned. To receive the
	// next page, you call ListPhoneNumbersOptedOut again using the NextToken string
	// received from the previous call. When there are no more records to return,
	// NextToken will be null.
	ListPhoneNumbersOptedOut(ctx context.Context, params *sns.ListPhoneNumbersOptedOutInput, optFns ...func(*sns.Options)) (*sns.ListPhoneNumbersOptedOutOutput, error)
	// Lists the platform application objects for the supported push notification
	// services, such as APNS and GCM (Firebase Cloud Messaging). The results for
	// ListPlatformApplications are paginated and return a limited list of
	// applications, up to 100. If additional records are available after the first
	// page results, then a NextToken string will be returned. To receive the next
	// page, you call ListPlatformApplications using the NextToken string received
	// from the previous call. When there are no more records to return, NextToken
	// will be null. For more information, see [Using Amazon SNS Mobile Push Notifications].
	//
	// This action is throttled at 15 transactions per second (TPS).
	//
	// [Using Amazon SNS Mobile Push Notifications]: https://docs.aws.amazon.com/sns/latest/dg/SNSMobilePush.html
	ListPlatformApplications(ctx context.Context, params *sns.ListPlatformApplicationsInput, optFns ...func(*sns.Options)) (*sns.ListPlatformApplicationsOutput, error)
	// Lists the calling Amazon Web Services account's current verified and pending
	// destination phone numbers in the SMS sandbox.
	//
	// When you start using Amazon SNS to send SMS messages, your Amazon Web Services
	// account is in the SMS sandbox. The SMS sandbox provides a safe environment for
	// you to try Amazon SNS features without risking your reputation as an SMS sender.
	// While your Amazon Web Services account is in the SMS sandbox, you can use all of
	// the features of Amazon SNS. However, you can send SMS messages only to verified
	// destination phone numbers. For more information, including how to move out of
	// the sandbox to send messages without restrictions, see [SMS sandbox]in the Amazon SNS
	// Developer Guide.
	//
	// [SMS sandbox]: https://docs.aws.amazon.com/sns/latest/dg/sns-sms-sandbox.html
	ListSMSSandboxPhoneNumbers(ctx context.Context, params *sns.ListSMSSandboxPhoneNumbersInput, optFns ...func(*sns.Options)) (*sns.ListSMSSandboxPhoneNumbersOutput, error)
	// Returns a list of the requester's subscriptions. Each call returns a limited
	// list of subscriptions, up to 100. If there are more subscriptions, a NextToken
	// is also returned. Use the NextToken parameter in a new ListSubscriptions call
	// to get further results.
	//
	// This action is throttled at 30 transactions per second (TPS).
	ListSubscriptions(ctx context.Context, params *sns.ListSubscriptionsInput, optFns ...func(*sns.Options)) (*sns.ListSubscriptionsOutput, error)
	// Returns a list of the subscriptions to a specific topic. Each call returns a
	// limited list of subscriptions, up to 100. If there are more subscriptions, a
	// NextToken is also returned. Use the NextToken parameter in a new
	// ListSubscriptionsByTopic call to get further results.
	//
	// This action is throttled at 30 transactions per second (TPS).
	ListSubscriptionsByTopic(ctx context.Context, params *sns.ListSubscriptionsByTopicInput, optFns ...func(*sns.Options)) (*sns.ListSubscriptionsByTopicOutput, error)
	// List all tags added to the specified Amazon SNS topic. For an overview, see [Amazon SNS Tags] in
	// the Amazon Simple Notification Service Developer Guide.
	//
	// [Amazon SNS Tags]: https://docs.aws.amazon.com/sns/latest/dg/sns-tags.html
	ListTagsForResource(ctx context.Context, params *sns.ListTagsForResourceInput, optFns ...func(*sns.Options)) (*sns.ListTagsForResourceOutput, error)
	// Returns a list of the requester's topics. Each call returns a limited list of
	// topics, up to 100. If there are more topics, a NextToken is also returned. Use
	// the NextToken parameter in a new ListTopics call to get further results.
	//
	// This action is throttled at 30 transactions per second (TPS).
	ListTopics(ctx context.Context, params *sns.ListTopicsInput, optFns ...func(*sns.Options)) (*sns.ListTopicsOutput, error)
	// Use this request to opt in a phone number that is opted out, which enables you
	// to resume sending SMS messages to the number.
	//
	// You can opt in a phone number only once every 30 days.
	OptInPhoneNumber(ctx context.Context, params *sns.OptInPhoneNumberInput, optFns ...func(*sns.Options)) (*sns.OptInPhoneNumberOutput, error)
	// Sends a message to an Amazon SNS topic, a text message (SMS message) directly
	// to a phone number, or a message to a mobile platform endpoint (when you specify
	// the TargetArn ).
	//
	// If you send a message to a topic, Amazon SNS delivers the message to each
	// endpoint that is subscribed to the topic. The format of the message depends on
	// the notification protocol for each subscribed endpoint.
	//
	// When a messageId is returned, the message is saved and Amazon SNS immediately
	// delivers it to subscribers.
	//
	// To use the Publish action for publishing a message to a mobile endpoint, such
	// as an app on a Kindle device or mobile phone, you must specify the EndpointArn
	// for the TargetArn parameter. The EndpointArn is returned when making a call with
	// the CreatePlatformEndpoint action.
	//
	// For more information about formatting messages, see [Send Custom Platform-Specific Payloads in Messages to Mobile Devices].
	//
	// You can publish messages only to topics and endpoints in the same Amazon Web
	// Services Region.
	//
	// [Send Custom Platform-Specific Payloads in Messages to Mobile Devices]: https://docs.aws.amazon.com/sns/latest/dg/mobile-push-send-custommessage.html
	Publish(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options)) (*sns.PublishOutput, error)
	// Publishes up to ten messages to the specified topic. This is a batch version of
	// Publish . For FIFO topics, multiple messages within a single batch are published
	// in the order they are sent, and messages are deduplicated within the batch and
	// across batches for 5 minutes.
	//
	// The result of publishing each message is reported individually in the response.
	// Because the batch request can result in a combination of successful and
	// unsuccessful actions, you should check for batch errors even when the call
	// returns an HTTP status code of 200 .
	//
	// The maximum allowed individual message size and the maximum total payload size
	// (the sum of the individual lengths of all of the batched messages) are both 256
	// KB (262,144 bytes).
	//
	// Some actions take lists of parameters. These lists are specified using the
	// param.n notation. Values of n are integers starting from 1. For example, a
	// parameter list with two elements looks like this:
	//
	// &AttributeName.1=first
	//
	// &AttributeName.2=second
	//
	// If you send a batch message to a topic, Amazon SNS publishes the batch message
	// to each endpoint that is subscribed to the topic. The format of the batch
	// message depends on the notification protocol for each subscribed endpoint.
	//
	// When a messageId is returned, the batch message is saved and Amazon SNS
	// immediately delivers the message to subscribers.
	PublishBatch(ctx context.Context, params *sns.PublishBatchInput, optFns ...func(*sns.Options)) (*sns.PublishBatchOutput, error)
	// Adds or updates an inline policy document that is stored in the specified
	// Amazon SNS topic.
	PutDataProtectionPolicy(ctx context.Context, params *sns.PutDataProtectionPolicyInput, optFns ...func(*sns.Options)) (*sns.PutDataProtectionPolicyOutput, error)
	// Removes a statement from a topic's access control policy.
	//
	// To remove the ability to change topic permissions, you must deny permissions to
	// the AddPermission , RemovePermission , and SetTopicAttributes actions in your
	// IAM policy.
	RemovePermission(ctx context.Context, params *sns.RemovePermissionInput, optFns ...func(*sns.Options)) (*sns.RemovePermissionOutput, error)
	// Sets the attributes for an endpoint for a device on one of the supported push
	// notification services, such as GCM (Firebase Cloud Messaging) and APNS. For more
	// information, see [Using Amazon SNS Mobile Push Notifications].
	//
	// [Using Amazon SNS Mobile Push Notifications]: https://docs.aws.amazon.com/sns/latest/dg/SNSMobilePush.html
	SetEndpointAttributes(ctx context.Context, params *sns.SetEndpointAttributesInput, optFns ...func(*sns.Options)) (*sns.SetEndpointAttributesOutput, error)
	// Sets the attributes of the platform application object for the supported push
	// notification services, such as APNS and GCM (Firebase Cloud Messaging). For more
	// information, see [Using Amazon SNS Mobile Push Notifications]. For information on configuring attributes for message
	// delivery status, see [Using Amazon SNS Application Attributes for Message Delivery Status].
	//
	// [Using Amazon SNS Application Attributes for Message Delivery Status]: https://docs.aws.amazon.com/sns/latest/dg/sns-msg-status.html
	// [Using Amazon SNS Mobile Push Notifications]: https://docs.aws.amazon.com/sns/latest/dg/SNSMobilePush.html
	SetPlatformApplicationAttributes(ctx context.Context, params *sns.SetPlatformApplicationAttributesInput, optFns ...func(*sns.Options)) (*sns.SetPlatformApplicationAttributesOutput, error)
	// Use this request to set the default settings for sending SMS messages and
	// receiving daily SMS usage reports.
	//
	// You can override some of these settings for a single message when you use the
	// Publish action with the MessageAttributes.entry.N parameter. For more
	// information, see [Publishing to a mobile phone]in the Amazon SNS Developer Guide.
	//
	// To use this operation, you must grant the Amazon SNS service principal (
	// sns.amazonaws.com ) permission to perform the s3:ListBucket action.
	//
	// [Publishing to a mobile phone]: https://docs.aws.amazon.com/sns/latest/dg/sms_publish-to-phone.html
	SetSMSAttributes(ctx context.Context, params *sns.SetSMSAttributesInput, optFns ...func(*sns.Options)) (*sns.SetSMSAttributesOutput, error)
	// Allows a subscription owner to set an attribute of the subscription to a new
	// value.
	SetSubscriptionAttributes(ctx context.Context, params *sns.SetSubscriptionAttributesInput, optFns ...func(*sns.Options)) (*sns.SetSubscriptionAttributesOutput, error)
	// Allows a topic owner to set an attribute of the topic to a new value.
	//
	// To remove the ability to change topic permissions, you must deny permissions to
	// the AddPermission , RemovePermission , and SetTopicAttributes actions in your
	// IAM policy.
	SetTopicAttributes(ctx context.Context, params *sns.SetTopicAttributesInput, optFns ...func(*sns.Options)) (*sns.SetTopicAttributesOutput, error)
	// Subscribes an endpoint to an Amazon SNS topic. If the endpoint type is HTTP/S
	// or email, or if the endpoint and the topic are not in the same Amazon Web
	// Services account, the endpoint owner must run the ConfirmSubscription action to
	// confirm the subscription.
	//
	// You call the ConfirmSubscription action with the token from the subscription
	// response. Confirmation tokens are valid for two days.
	//
	// This action is throttled at 100 transactions per second (TPS).
	Subscribe(ctx context.Context, params *sns.SubscribeInput, optFns ...func(*sns.Options)) (*sns.SubscribeOutput, error)
	// Add tags to the specified Amazon SNS topic. For an overview, see [Amazon SNS Tags] in the Amazon
	// SNS Developer Guide.
	//
	// When you use topic tags, keep the following guidelines in mind:
	//
	//   - Adding more than 50 tags to a topic isn't recommended.
	//
	//   - Tags don't have any semantic meaning. Amazon SNS interprets tags as
	//     character strings.
	//
	//   - Tags are case-sensitive.
	//
	//   - A new tag with a key identical to that of an existing tag overwrites the
	//     existing tag.
	//
	//   - Tagging actions are limited to 10 TPS per Amazon Web Services account, per
	//     Amazon Web Services Region. If your application requires a higher throughput,
	//     file a [technical support request].
	//
	// [Amazon SNS Tags]: https://docs.aws.amazon.com/sns/latest/dg/sns-tags.html
	// [technical support request]: https://console.aws.amazon.com/support/home#/case/create?issueType=technical
	TagResource(ctx context.Context, params *sns.TagResourceInput, optFns ...func(*sns.Options)) (*sns.TagResourceOutput, error)
	// Deletes a subscription. If the subscription requires authentication for
	// deletion, only the owner of the subscription or the topic's owner can
	// unsubscribe, and an Amazon Web Services signature is required. If the
	// Unsubscribe call does not require authentication and the requester is not the
	// subscription owner, a final cancellation message is delivered to the endpoint,
	// so that the endpoint owner can easily resubscribe to the topic if the
	// Unsubscribe request was unintended.
	//
	// Amazon SQS queue subscriptions require authentication for deletion. Only the
	// owner of the subscription, or the owner of the topic can unsubscribe using the
	// required Amazon Web Services signature.
	//
	// This action is throttled at 100 transactions per second (TPS).
	Unsubscribe(ctx context.Context, params *sns.UnsubscribeInput, optFns ...func(*sns.Options)) (*sns.UnsubscribeOutput, error)
	// Remove tags from the specified Amazon SNS topic. For an overview, see [Amazon SNS Tags] in the
	// Amazon SNS Developer Guide.
	//
	// [Amazon SNS Tags]: https://docs.aws.amazon.com/sns/latest/dg/sns-tags.html
	UntagResource(ctx context.Context, params *sns.UntagResourceInput, optFns ...func(*sns.Options)) (*sns.UntagResourceOutput, error)
	// Verifies a destination phone number with a one-time password (OTP) for the
	// calling Amazon Web Services account.
	//
	// When you start using Amazon SNS to send SMS messages, your Amazon Web Services
	// account is in the SMS sandbox. The SMS sandbox provides a safe environment for
	// you to try Amazon SNS features without risking your reputation as an SMS sender.
	// While your Amazon Web Services account is in the SMS sandbox, you can use all of
	// the features of Amazon SNS. However, you can send SMS messages only to verified
	// destination phone numbers. For more information, including how to move out of
	// the sandbox to send messages without restrictions, see [SMS sandbox]in the Amazon SNS
	// Developer Guide.
	//
	// [SMS sandbox]: https://docs.aws.amazon.com/sns/latest/dg/sns-sms-sandbox.html
	VerifySMSSandboxPhoneNumber(ctx context.Context, params *sns.VerifySMSSandboxPhoneNumberInput, optFns ...func(*sns.Options)) (*sns.VerifySMSSandboxPhoneNumberOutput, error)
}
